import { NextRequest, NextResponse } from 'next/server';

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { prompt, model } = body;

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    if (!GEMINI_API_KEY) {
      return NextResponse.json({ error: "Gemini API key not configured" }, { status: 500 });
    }

    // Use gemini-2.5-flash model
    const modelName = "gemini-2.5-flash";
    const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${GEMINI_API_KEY}`;

    const response = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8192,
          responseMimeType: "application/json",
          responseSchema: {
            type: "OBJECT",
            properties: {
              subject: {
                type: "STRING",
                description: "A highly attractive, human-sounding subject line. MUST be PLAIN TEXT ONLY — absolutely NO markdown, NO asterisks (*), NO bold (**), NO underscores (_), NO hashtags (#), NO special formatting characters. Just clean, readable plain text."
              },
              body: {
                type: "STRING",
                description: "The complete, untruncated email body. Must be deeply personalized using the candidate's resume details. Use plain text with markdown formatting (** for bold, newlines as line breaks). Do NOT use HTML tags. Every paragraph must reference specific resume achievements. Follow the tone_style from generation_preferences EXACTLY — match the writing style, vocabulary level, and energy to what the user specified."
              }
            },
            required: ["subject", "body"]
          }
        }
      })
    });

    // Read raw text first to avoid JSON parse errors on empty/malformed bodies
    const rawText = await response.text();

    if (!response.ok) {
      console.error("Gemini API error response:", response.status, rawText.substring(0, 500));
      let errorMsg = `Gemini API returned ${response.status}`;
      try {
        const errData = JSON.parse(rawText);
        errorMsg = errData.error?.message || errorMsg;
      } catch { }
      return NextResponse.json({ error: errorMsg }, { status: 500 });
    }

    if (!rawText || rawText.trim().length === 0) {
      return NextResponse.json({ error: "Empty response from Gemini API" }, { status: 500 });
    }

    let data: any;
    try {
      data = JSON.parse(rawText);
    } catch (parseErr) {
      console.error("Failed to parse Gemini response:", rawText.substring(0, 500));
      return NextResponse.json({ error: "Invalid JSON response from Gemini API" }, { status: 500 });
    }

    const text = data.candidates?.[0]?.content?.parts?.[0]?.text || "";
    const finishReason = data.candidates?.[0]?.finishReason || "";

    console.log("[AI Debug] finishReason:", finishReason);
    console.log("[AI Debug] text length:", text.length);
    console.log("[AI Debug] text preview:", text.substring(0, 300));

    if (!text) {
      const blockReason = finishReason || data.promptFeedback?.blockReason;
      if (blockReason) {
        return NextResponse.json({ error: `Content blocked: ${blockReason}` }, { status: 400 });
      }
      return NextResponse.json({ error: "No text generated by Gemini" }, { status: 500 });
    }

    if (finishReason === "MAX_TOKENS") {
      console.warn("[AI Warning] Response was truncated due to MAX_TOKENS limit");
    }

    return NextResponse.json({ text });

  } catch (error: any) {
    console.error("AI Generation error:", error?.message || error);
    return NextResponse.json({ error: error?.message || "Internal server error" }, { status: 500 });
  }
}
